### ISSUE TITLE
[補充]捲軸特效選單-scrollpos勾子的應用

### ISSUE THREAD

**Issue by eyesofkids** [eyesofkids/MFEE13#35]
> 參考：[use-scroll-position](https://github.com/n8tb1t/use-scroll-position#readme)

範例檔案：https://github.com/eyesofkids/MFEE13/tree/main/%E5%85%B6%E5%AE%83%E7%AF%84%E4%BE%8B/React/%E6%8D%B2%E8%BB%B8%E7%89%B9%E6%95%88%E9%81%B8%E5%96%AE-scrollpos%E5%8B%BE%E5%AD%90%E7%9A%84%E6%87%89%E7%94%A8

## 安裝勾子

```sh
yarn add @n8tb1t/use-scroll-position
```

## 使用在要測試目前捲軸位置的元件上

```jsx
import { useScrollPosition } from '@n8tb1t/use-scroll-position'
//...
function MyNavbar(props) {
  // 兩個狀態切換
  const [show, setShow] = useState(true)

  useScrollPosition(({ prevPos, currPos }) => {
    // 這裡可以監視目前的捲軸狀態
    console.log(currPos.x)
    console.log(currPos.y)
    if (currPos.y < -200) {
      setShow(false)
    } else {
      setShow(true)
    }
  })
```

## 加入切換的css樣式類別

```jsx
<Navbar
        collapseOnSelect
        expand="lg"
        bg="primary"
        variant="dark"
        fixed="top"
        className={
          show ? 'nav-normal' : 'nav-hide'
        }
      >
```

> custom.scss

```scss

.nav-normal {
  visibility: visible;
  transition: all 200ms ease-in;
  transform: none;
}

.nav-hide {
  visibility: hidden;
  transition: all 200ms ease-out;
  transform: translate(0, -100%);
}

.nav-shink-normal {
  padding-top: 1.5em;
  padding-bottom: 1.5em;
  transition: 0.4s; /* Adds a transition effect when the padding is decreased */
}

.nav-shink-hide {
  padding-top: 0.3em;
  padding-bottom: 0.3em;
  transition: 0.4s; /* Adds a transition effect when the padding is decreased */
}
```

![scrollpos-1](https://user-images.githubusercontent.com/433742/103338827-9d65d080-4aba-11eb-9fcb-91ef74ea0296.gif)

![scrollpos-2](https://user-images.githubusercontent.com/433742/103338879-cc7c4200-4aba-11eb-975e-4b58d7507067.gif)
